// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package followupmicroflow.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import followupmicroflow.FUEHelpers;

/**
 * This action checks if an object with the given ID can be found in the database
 */
public class IsObjectExisting extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.Long objectID;

	public IsObjectExisting(IContext context, java.lang.Long objectID)
	{
		super(context);
		this.objectID = objectID;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		return FUEHelpers.isObjectExisting(getContext(), objectID);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "IsObjectExisting";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
