// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package followupmicroflow.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import followupmicroflow.FollowUpThreadPool;

public class JA_FollowUpMicroflow_GetPoolSize extends CustomJavaAction<java.lang.Long>
{
	public JA_FollowUpMicroflow_GetPoolSize(IContext context)
	{
		super(context);
	}

	@Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		return new Long(FollowUpThreadPool.getInstance().getPoolSize());
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "JA_FollowUpMicroflow_GetPoolSize";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
